repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: go-test-repo-mod
        args: [-race, -count=1]
      - id: go-vet-repo-mod
      - id: go-fumpt-repo
        args: [-l, -w]
      # TODO: Fix the error:
      # Error: can't load config: can't read viper config: open .golangci.yaml: too many levels of symbolic links
      # Failed executing command with error: can't load config: can't read viper config: open .golangci.yaml: too many levels of symbolic links
      # - id: golangci-lint-repo-mod
      #   args: [--config, .golangci.yaml, --, --fix]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
