repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: go-test-repo-mod
        args: [-race, -count=1]
      - id: go-vet-repo-mod
      - id: go-fumpt-repo
        args: [-l, -w]
      - id: golangci-lint-repo-mod
        args: [--config, .golangci.yaml, --, --fix]

  # If this is used for business, a free license is required.
  # It can be obtained from https://gitleaks.io/products.html
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
