name: Test

on: [push, pull_request]

permissions:
  # Needed to read the content of the repository
  contents: read
  # Needed for the static analysis result upload
  security-events: write
  # Needed for golangci-lint for the only-new-issues flag
  pull-requests: read
  # Needed to annotate the code with the scan results > https://github.blog/2018-12-14-introducing-check-runs-and-annotations/
  checks: write

jobs:
  test:
    uses: lvlcn-t/meta/.github/workflows/test.yml@main
    with:
      go_version_file: go.mod
      golangci_config: .golangci.yaml
      private_go_server: ""
      before_tests: ""
      additional_args: -v
    secrets:
      PRIVATE_GO_SERVER_TOKEN: ${{ secrets.PRIVATE_GO_SERVER_TOKEN }}
